-- create shopping table 
CREATE TABLE t_user (
iuser INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
uid VARCHAR(15) UNIQUE NOT NULL,
upw VARCHAR(100) NOT NULL,
nm VARCHAR(10) NOT NULL,
hnum VARCHAR(12) NOT NULL,
ph VARCHAR(13) NOT NULL,
addr VARCHAR(50) NOT NULL,
gender TINYINT UNSIGNED CHECK(gender IN (1, 2)),
joindata DATETIME DEFAULT CURRENT_TIMESTAMP,
profileimg VARCHAR(50) NOT NULL,
cardinfo VARCHAR(100) NOT NULL
);
CREATE TABLE merchandise (
iboard INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
itemimg VARCHAR(50) NOT NULL,
price INT UNSIGNED NOT NULL,
color VARCHAR(15) NOT NULL,
size INT UNSIGNED NOT NULL,
sale INT UNSIGNED NOT NULL,
num INT UNSIGNED NOT NULL
);
CREATE TABLE coupon (
icoupon INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
cpnum VARCHAR(50) NOT NULL,
indexnum TINYINT UNSIGNED CHECK(indexnum IN (1, 2))
);
CREATE TABLE t_board_category (
icategory INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
categorynm VARCHAR(20) NOT NULL
);
CREATE TABLE t_board_wirte (
iboard INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
ctnt VARCHAR(1000) NOT NULL,
img VARCHAR(100) NOT NULL,
rdt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
mdt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
hits INT UNSIGNED NOT NULL DEFAULT 0
);
CREATE TABLE cart (
icart INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
items VARCHAR(50) NOT NULL,
num INT UNSIGNED NOT NULL,
size VARCHAR(10) NOT NULL
);
CREATE TABLE addrinfo (
iaddr INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
addr VARCHAR(30) NOT NULL,
addrnum VARCHAR(10) NOT NULL,
baddr VARCHAR(20) NOT NULL,
oaddr VARCHAR(20) NOT NULL,
hnum VARCHAR(12) NOT NULL,
ph VARCHAR(13) NOT NULL,
automsg VARCHAR(50) NOT NULL
);